### ISSUE TITLE
Model run into "Syntax error: Multiple definitions for WITH "..."" error

### ISSUE THREAD

**Issue by rafaelkrysciak** [Teradata/dbt-teradata#161]
### Describe the Bug
We encountered a Teradata syntax error while executing a model. The model structure is as follows:

```sql
WITH
TEST1 AS (
    SELECT 1 AS Id
),
TEST2 AS (
    SELECT * FROM TEST1 AS AGGR1
),
TEST3 AS (
    SELECT * FROM TEST2 AS AGGR1
)

SELECT * FROM TEST3;
```

This query works fine on its own. However, when the query is wrapped by the adapter into an outer query `SELECT * FROM ( ... ) AS D`, it results in a syntax error. The wrapped query looks like this:

```sql
SELECT *
FROM (
    WITH
    TEST1 AS (
        SELECT 1 AS Id
    ),
    TEST2 AS (
        SELECT * FROM TEST1 AS AGGR1
    ),
    TEST3 AS (
        SELECT * FROM TEST2 AS AGGR1
    )
    
    SELECT * FROM TEST3
) AS D;
```

The Teradata parser throws the following error for this query: `[Error 3706] Syntax error: Multiple definitions for WITH "AGGR1"`.

Interestingly, if there is a comment before the `WITH` keyword, the query works fine. The issue arises when comments are removed from the models, causing them to stop working. This behavior is related to the code in the `dbt-teradata` adapter:
https://github.com/Teradata/dbt-teradata/blob/6cc97b2470e6465cc3fa6df4bb2334966600e1b0/dbt/include/teradata/macros/adapters.sql#L69-L74

Although we can rewrite our transformations to have unique aliases, the expectation is that it should be possible to use the same aliases in multiple CTEs.

We are unsure if this is a bug in Teradata or the `dbt-teradata` connector. Your assistance in resolving this issue would be appreciated.

### Steps to Reproduce
1. Use the provided query in a model.
2. Run the query without a comment before the `WITH` statement; it will fail.
3. Add a comment before the `WITH` statement and run it again; it will succeed.

### Expected Behavior
The provided query should execute without failure, regardless of the presence of comments.

### Screenshots and Log Output
If applicable, add screenshots or log output to help explain your problem.

**The output of `dbt --version`:**
```
Core:
  - installed: 1.7.11
  - latest:    1.8.0  - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - teradata: 1.7.2 - Up to date!
```

**The operating system you're using:**
Windows 11

**The output of `python --version`:**
Python 3.11.3

**Comment by tallamohan** [comment]
This particular issue has been resolved, and the fix is available in the dbt-teradata 1.7.3 release.
